### ISSUE TITLE
Add examples/docs

### ISSUE THREAD

**Issue by greenbigfrog** [ddfreyne/glove#1]
Hi!
I might like to use your shard, but it's not that helpful without any examples.

For docs maybe just link to https://crystal-docs.org/ddfreyne/glove/

(I'm aware that this is quite new project, but it might be good if you ahve sth to track it :smile: )

**Comment by denisdefreyne** [comment]
Hi! I’ve updated the README to add an example.

Mind you: the code in this repository is experimental and there are no guarantees about stability. There are no guarantees that I’ll continue working on this and that it’ll become usable.

**Comment by greenbigfrog** [comment]
Thanks!
