### ISSUE TITLE
Tween kind as an abstract class?

### ISSUE THREAD

**Issue by Qard** [ddfreyne/glove#17]
@ddfreyne What do you think of changing `Glove::Tween::Kind` so, rather than an enum, it is a module containing classes that each implement a single abstract class with a `calc(lf)` method? This would allow for easy creation of custom tweening algorithms.

I just wanted to get your thoughts on it before I make a PR for it as it *would* be a significant breaking change.

**Comment by denisdefreyne** [comment]
Yes, that definitely makes sense!

(I’m not sure how I ended up with an enum-based implementation rather than an OO one.)
