### ISSUE TITLE
library not found for -lglfw3

### ISSUE THREAD

**Issue by Sphaerus** [ddfreyne/glove#20]
hey guys, i get this error whenever i try to run any glove related code. crystal itself works fine, i can execute code without issues, but with glove it always gives me this.
homebrew tells me it doesnt know any packages like this. Is glove just outdated?

**Comment by denisdefreyne** [comment]
Hey @Sphaerus — did you manage to solve this? `brew install glfw` should do the trick.

**Comment by frollo** [comment]
@ddfreyne I know I'm late for this, but I've just tried to start a simple glove project and I get the same error on Mac. Using `brew install glfw` does not fix it. I'll try a couple more solutions and keep you posted (also, if you have any idea about what I could try...).

**Comment by frollo** [comment]
It seems that `brew install glfw` was not enough, it has to be installed from sources. So, if anybody gets this problem again, the solution seems to be to install both `glfw` and `glew` from sources (`-s` option in brew). This is probably some weird behavior on brew's side.
