### ISSUE TITLE
Error using stbi lib

### ISSUE THREAD

**Issue by bararchy** [ddfreyne/glove#3]
Trying to build the example in the README I get this error:

```bash
G-love5858T-exture.o: In function `from':
/home/unshadow/Desktop/git-projects/TestGame/lib/glove/src/texture.cr:7: undefined reference to `stbi_load'
/home/unshadow/Desktop/git-projects/TestGame/lib/glove/src/texture.cr:34: undefined reference to `stbi_image_free'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "/home/unshadow/Desktop/git-projects/TestGame/TestGame" "${@}"  -rdynamic  -lGLEW -lGLU -lGL -lglfw -L/home/unshadow/Desktop/git-projects/TestGame/lib/glove/src/stb_image/../ext -lstb_image -lpcre -lm -lgc -lpthread /usr/lib/crystal/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`

```

**Comment by denisdefreyne** [comment]
This might be because the repo included the libstb_image build artifact by mistake (fixed in 381bd57ab7f1af35abff76e9e465fd2428174427).

If the problem persists, could you let me know

* which OS you are using
* which version of Crystal you are using

?

**Comment by denisdefreyne** [comment]
I’m not able to reproduce this issue.

FYI: I have updated the usage instructions for Glove (the README was missing documentation on copying the shaders): https://github.com/ddfreyne/glove#usage

**Comment by bararchy** [comment]
Hmmm indeed maybe I didn't copy the shadres , I'll test again in the morning and will let you know , thanks for checking in :)

**Comment by bararchy** [comment]
Trying to test fails with: https://github.com/ddfreyne/glove/issues/4

**Comment by denisdefreyne** [comment]
This *should* be resolved now, provided that you do a clean build of your app, with the latest version of Glove.

**Comment by bararchy** [comment]
Working, thanks :)
