### ISSUE TITLE
Event handling

### ISSUE THREAD

**Issue by bararchy** [ddfreyne/glove#5]
It would be really nice to have a wiki (or readme) info regarding handling of events.

Pressed key, or mouse click, etc...

**Comment by denisdefreyne** [comment]
The event handling isn’t in a state where I’d like it to be—the API seems clunky.

Documentation is missing in general, but that is definitely something that’ll need to be there at some point.

**Comment by bararchy** [comment]
That's totally acceptable for the state of this project , even a small example of how to catch something will be awesome .

Also , does glove use some kind of `main loop` where I should put all my stuff in ? Or is `.run` does the actual loop

**Comment by denisdefreyne** [comment]
I believe looking at the examples in the [Inari](https://github.com/ddfreyne/inari) repository is helpful for finding out how to do things.

The main loop in Glove is implicit. If you want to run code on entities regularly, there’s the possibly to create a System:

```crystal
class VelocityComponent < Glove::Component
  property :x
  property :y

  def initialize(@x : Float32, @y : Float32)
  end
end

class UpdatePositionSystem < Glove::System
  def update(delta_time, space, app)
    es = space.entities.select { |e| e[VelocityComponent]? && e[Glove::Components::Transform]? }
    es.each do |e|
      vel = e[VelocityComponent]
      tr = e[Glove::Components::Transform]

      tr.translate_x += vel.x * delta_time
      tr.translate_y += vel.y * delta_time
    end
  end
end

# …

scene =
  Glove::Scene.new.tap do |scene|
    scene.spaces << Glove::Space.new.tap do |space|
      # …
      space.systems << UpdatePositionSystem.new
    end
  end
```
