### ISSUE TITLE
Different classes of Point add and subtract?

### ISSUE THREAD

**Issue by Qard** [ddfreyne/glove#9]
Is there some reason `Glove::Point::+` creates an instance of `self.class` while `Glove::Point::-` creates an instance of `Glove::Vector`? I'm wondering if I'm missing something or if `-` could be changed to `self.class` too.

https://github.com/ddfreyne/glove/blob/master/src/point.cr#L8-L14

**Comment by denisdefreyne** [comment]
I think it makes sense for `point - point = vector`, but `point + point = point` probably does not make sense. Changing the latter to `point + vector = point` likely makes more sense. WDYT?

```
point + vector = point
point - vector = point

point + point = (not possible)
point - point = vector
```

Other operations likely also make sense, but haven’t been implemented (yet):

```
point * scalar = point
point / scalar = point

vector * scalar = vector
vector / scalar = vector
```

**Comment by denisdefreyne** [comment]
I believe that 06a843347974371a44ca9242794e3441c546508b solves this issue.

**Comment by denisdefreyne** [comment]
(and 1802028ded2a1248692b9274ea5102cd4551f526 for a bit more consistency)
